apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
  namespace: pg-multizone
type: Opaque
stringData:
  # Replace or encrypt with SealedSecret / Vault in production
  POSTGRES_PASSWORD: Password123!
